config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resource :basket, only: :show do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :items

  def total_price
    items.sum(:price).round(2)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :basket
  validate :items_number
  validates :price, numericality: true

  def items_number
    if basket.items.count > 9 && basket.user.role == 'user'
      errors.add(:message, "To many items in basket")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :basket, dependent: :destroy

  after_create :create_basket

  def self.all_items
    find_by(role: 'admin').basket.items.all
  end

  def items_count
    basket.items.count
  end

  def self.create_basket
    Basket.create!(user: current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :find_basket

  def show
    @all_items = User.all_items
    @price = @basket.total_price
  end

  private

  def find_basket
    @basket ||= current_user.basket
  end

  def basket_params
    params.permit(:price, :title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @basket = current_user.basket
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_basket

  def create
    @item = @basket.items.new(item_params)
    flash[:notice] = @item.errors.messages[:message].first unless @item.save
    redirect_to @basket
  end

  def destroy
    @item = @basket.items.find(params[:id])
    @item.destroy
    redirect_to @basket
  end

  private

  def find_basket
    @basket ||= current_user.basket
  end

  def item_params
    params.permit(:title, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
  def main_caption
    current_user.role == 'user' ? 'My basket' : 'On store'
  end

  def basket_caption
    current_user.role == 'user' ? 'basket' : 'store'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/baskets/show.html.slim
.text-center
  h4 #{ main_caption }: #{ current_user.items_count || 0} items
  - if current_user.role == 'user'
    h4 with total price: #{ @price }.
p
  = render @basket.items
  - if current_user.role == 'admin'
    br/
    h5 Add item:
    = form_with url: basket_items_path, local: true, :html => { :class => "form-horizontal center" } do |f|
      .form-group
        = f.label :title, "Title:"
        = f.text_field :title, class: "form-control"
      .form-group
        = f.label :price, "Price:"
        = f.text_field :price, class: "form-control"
      .form-group
      = f.submit "Submit", class: "btn btn-default btn-primary"
  - else
    .text-center
      h4 All items:
    p
      = render @all_items

app/views/home/index.html.slim
h3 Welcome #{current_user.email}
= link_to "My #{ basket_caption }", basket_path

app/views/items/_item.html.slim
.container
  .row
    .text-center.col-md-5.col-lg-5
      strong Item:
      =< item.title
    .text-center.col-md-3.col-lg-3
      strong Price:
      =< item.price
    - if item.basket == current_user.basket
      .text-center.col-md-2.col-lg-2
        = link_to "Remove from #{ basket_caption }", basket_item_path(id: item), method: :delete, data: { confirm: 'Are you sure?' }
    - else
      .text-center.col-md-2.col-lg-2
        = link_to 'Add to basket', basket_items_path(price: item.price, title: item.title), method: :post
hr/

app/views/layouts/application.html.slim
doctype html
html
  head
    title Test
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      - if current_user
        =< link_to "#{current_user.email}", root_path 
        =< link_to 'Edit profile', edit_user_registration_path(current_user.id)      
        =< link_to 'Logout', destroy_user_session_path, method: :delete
      p.notice= notice
      p.alert= alert
      = yield